### ISSUE TITLE
installation and documentation snafu

### ISSUE THREAD

**Issue by seltmann** [iDigBio/ridigbio#18]
Hi all,
Hope I am adding an issue to the right spot. Trouble today installing, had to download binaries directly from CRAN and then install from download. In addition I had to include some dependancies that didnt fire automatically, even with dependecies=TRUE. I typically have no trouble installing other packages from CRAN.

install.packages("/Users/kseltmann/Downloads/ridigbio_0.2.2.tgz", repos=NULL, dependencies=TRUE)
library(ridigbio)
install.packages("jsonlite")
install.packages("rjson")

On Mac 10.7.5
R version 3.0.1

Thank yoU!

**Comment by mjcollin** [comment]
When I first fire up rstudio, install.packages("ridigbio") does say:

```
Warning in install.packages :
  package ‘ridigbio’ is not available (for R version 3.2.0)
```

But after I choose a CRAN mirror with chooseCRANmirror() it works. My install is a little odd because I used the RA distribution of R so when I first start up this is what I have for repos:

```
> getOption("repos")
                                                 CRAN 
"http://mran.revolutionanalytics.com/snapshot/2015-05-01"
```

What do you have for getOption("repos")?

**Comment by seltmann** [comment]
When I first tried to install:
install.packages("ridigbio")

I got this error:
package ‘ridigbio’ is available as a source package but not as a binary

Warning in install.packages :
  package ‘ridigbio’ is not available (as a binary package for R version 3.1.3)

but if I try to run an example afterward (because it was only a warning)

> idig_search_records(rq=list(genus="acer"))
> Error: could not find function "idig_search_records"
> 
> getOption("repos")
>                      CRAN 
> "http://cran.rstudio.com" 
> attr(,"RStudio")
> [1] TRUE

**Comment by fmichonneau** [comment]
It is because the binary version of the package is not yet available for
the older version of R. If you upgrade to 3.2.0 then you'd be OK.

**Comment by seltmann** [comment]
maybe add to documentation

**Comment by mjcollin** [comment]
Regarding the no idig_search_records() function, did you load the library? :)

If you did, perhaps you have a copy of the version from Francois' original repo which used idig_search(). If that function exists that you'll have to clean out that version first.

**Comment by seltmann** [comment]
augh! with that I officially put on my "duh" hat.
