### ISSUE TITLE
geopoint and `data.` fields don't work now

### ISSUE THREAD

**Issue by sckott** [iDigBio/ridigbio#20]
don't work for me at least, and I have latest from github.  working on a fix...

**Comment by sckott** [comment]
@mjcollin not sure if you'll like my changes - i added `rbind_fill` fxn, a port form `plyr` package - so that fields that are missing in each record are simply dropped, then we can put them all together with `rbind_fill` -

in addition, geopoint was being returned because the indexing to geopoint fields was broken

didn't address `data.` fields, but those don't work now either

**Comment by sckott** [comment]
let me know if you'd entertain a PR with the changes i made https://github.com/sckott/ridigbio/tree/search-fix

**Comment by mjcollin** [comment]
I was fixing your other doc issue when I noticed as well. The indexing method Francois put in doesn't match the pattern I was using before so this was introduced with his lapply speedup. I'll look at your PR.

**Comment by sckott** [comment]
there's some whitespace changes - sorry about that, i'll be more careful next time, though this hides them: https://github.com/iDigBio/ridigbio/compare/master...sckott:search-fix?w=1

**Comment by mjcollin** [comment]
Still working on this.

**Comment by mjcollin** [comment]
I went with using plyr as you did, thanks. I ended up doing more if() statements to deal with geopoint that I would have liked but plyr let me do them at a fairly outer level of nesting so it seems not to be bad.

Performance is ~85 seconds for 100k records with the default fields on a 100 MBs connection which I think is adequate for the purpose.
