### ISSUE TITLE
Tests fail on CRAN

### ISSUE THREAD

**Issue by mjcollin** [iDigBio/ridigbio#22]
Report from CRAN mainainer Kurt Hornik Kurt.Hornik@wu.ac.at
Fri 7/10/2015 3:09 PM

Dear maintainer,

This now seems to fail its checks with
- checking tests ... ERROR
  Running the tests in ‘tests/testthat.R’ failed.
  Last 13 lines of output:
  1. Failure (at test-idig_search_records.R#36): (unknown) ----------------------
     substr(df[["specificepithet"]], 1, 1) > "m" isn't true
  2. Failure (at test-idig_search_records.R#39): (unknown) ----------------------
     substr(df[["uuid"]], 1, 2) == "00" isn't false
  3. Failure (at test-idig_search_records.R#40): (unknown) ----------------------
     substr(df[["specificepithet"]], 1, 1) < "m" isn't true
  
  Error in idig_search(rq = rq, fields = fields, max_items = max_items,  : 
    Search would return more than 1e+05 results. See max_items argument.
  Calls: test_check ... sys.source2 -> eval -> eval -> idig_search_records -> idig_search
  Execution halted

Can you pls fix as necessary?

Best
-k

**Comment by mjcollin** [comment]
I believe the API was having issues this day and the error reports match that. Tests pass now, there didn't seem to be anything wrong with them.

**Comment by fmichonneau** [comment]
It's best to use

`skip_on_cran()` (from testthat)

in your tests, so these tests don't get run on CRAN and you avoid this kind
of hassle.

On Mon, Jul 13, 2015 at 4:41 PM, Matthew J Collins <notifications@github.com

**Comment by mjcollin** [comment]
The tests for this package check that it returns the "right" data from our API. As the data in our repository changes, what is "right" changes too so I have to update the tests periodically.

I've submitted an updated version of the package with updated tests for now but it looks like what I really should do is skip most of the tests on CRAN since this is just going to happen periodically. Just repeatedly updating the package tests really doesn't help anyone.

**Comment by mjcollin** [comment]
Dear maintainer,
This currently seems to fail with
- checking tests ... ERROR
  Running the tests in ‘tests/testthat.R’ failed.
  Last 13 lines of output:
  !is.null(df[1, "data.ac:accessURI"]) && df[1, "data.ac:accessURI"] != "NA" isn't true
  1. Failure (at test-idig_top_media.R#31): (unknown) ----------------------------
     top$itemCount > 0 isn't true
  
  testthat results ================================================================
  OK: 106 SKIPPED: 0 FAILED: 3
  1. Failure (at test-idig_count_media.R#19): (unknown) 
  2. Failure (at test-idig_search_media.R#36): (unknown) 
  3. Failure (at test-idig_top_media.R#31): (unknown) 
  
  Error: testthat unit tests failed
  Execution halted

**Comment by mjcollin** [comment]
Currently this is the only error:
1. Failure (at test-idig_search_media.R#36): (unknown) -------------------------
   !is.null(df[1, "data.ac:accessURI"]) && df[1, "data.ac:accessURI"] != "NA" isn't true

**Comment by mjcollin** [comment]
Tests that run against the web API are now wrapped in a testthat::skip_on_cran() block so they will no longer throw errors when the data drifts from what the tests were written against.

Will roll out in 0.4.0 release by 11/20. Still waiting to close some more issues.
