### ISSUE TITLE
how to cite

### ISSUE THREAD

**Issue by seltmann** [iDigBio/ridigbio#27]
Hi!
I am adding a citation for ridigbio in a paper I am working on. How would you like me to cite?

Katja

**Comment by mjcollin** [comment]
Michonneau F, Collins M, Chamberlain SA (2015). ridigbio: An interface to iDigBio's search API that allows downloading specimen records. R package version 0.3.1. https://github.com/iDigBio/ridigbio

Leaving open to remind me to add a citation function or documentation note next release cycle.
