### ISSUE TITLE
Retrieve dwc:habitat with idig_search_records?

### ISSUE THREAD

**Issue by pbuttigieg** [iDigBio/ridigbio#4]
Greetings, 

I've tried to pull habitat with the idig_search_records() function, but receive NAs - are all fields queryable in this package?

Many thanks!

**Comment by mjcollin** [comment]
Habitat is often not filled in so having lots of NAs would be expected. However, habitat is also a field that is not indexed in Elasticsearch[1] so it isn't currently processed and returned by the R client.

If you're interested in working directly with the API, you can see this query returns the kind of information you're looking for, it's only the R client that doesn't add the fields to the dataframe:

http://beta-search.idigbio.org/v2/search/?rq={%22scientificname%22:%22abietinella%20abietina%22}&fields=[%22uuid%22,%22scientificname%22,%22data.dwc:habitat%22]

When we started writing the R library, the unindexed terms were hard to process using the technique we picked first. It's easier now that we've switched techniques so I'll try to get this up before the hackathon.

​[1] https://github.com/iDigBio/idigbio-search-api/wiki/Index-Fields
