### ISSUE TITLE
Documentation on Media records and Records relationship is needed

### ISSUE THREAD

**Issue by mgaynor1** [iDigBio/ridigbio#47]
Additional documentation is needed to make sure the link between Records and Media records is clearly stated. Please see comment here: https://github.com/sagesteppe/SeedPhenology/issues/1#issuecomment-1898744072

**Comment by jbennettufl** [comment]
Where are you getting the information about when IDigBio stopped accepting images from?

**Comment by mgaynor1** [comment]
I think you are missing the point of those comments and this issue. The user did not know which field connected Records and Media records. One would think the UUID, but we assign different UUIDs to media records and records. The UUID for the matching record is stored under "records" and this should be added to the documentation of both searches.

**Comment by CatChapman** [comment]
hiiiii 👋 she got the information from me, and I think I was a year off actually. here's a ticket from Jan 2020 mentioning the discontinuation of the image upload API. https://redmine.idigbio.org/issues/3411

not to derail, I just wanted to provide some context as to where she got that figure.

**Comment by wolfspider** [comment]
Ok, no problem yeah that definitely makes sense.

**Comment by mgaynor1** [comment]
I opened a new branch to improve documentation and add a pkgdown site. I hope to incorporate some of [Erica's tutorials](https://github.com/biodiversity-specimen-data/specimen-data-use-case/tree/master/_solution) as articles.

I will open a pull request when it is ready to be reviewed.

**Comment by mgaynor1** [comment]
Added and we are currently pushing this to CRAN
