### ISSUE TITLE
Pass on attributes in output

### ISSUE THREAD

**Issue by sckott** [iDigBio/ridigbio#7]
Seems useful at least to give back `itemCount`, and maybe `lastModified` too if its useful. 

Could give back a list instead of the current data.frame, with slots for `itemCount`, `lastModified`, and `data` (the data.frame)

Or alternatively as attributes on the data.frame

**Comment by mjcollin** [comment]
How about attributes since that is where I was going to put the attribution block? attr(df)['itemCount'] feels nicer to me at least.

**Comment by sckott** [comment]
Sounds good
